name: Scrainee
options:
  bundleIdPrefix: com.cpohl
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "6.24.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  Scrainee:
    type: application
    platform: macOS
    sources:
      - path: Scrainee
        excludes:
          - "**/*.xcassets"
          - "Resources/**"
    resources:
      - path: Scrainee/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cpohl.scrainee
        INFOPLIST_FILE: Scrainee/Info.plist
        CODE_SIGN_ENTITLEMENTS: Scrainee/Scrainee.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        # Menu Bar App (kein Dock-Icon)
        INFOPLIST_KEY_LSUIElement: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - package: GRDB
      - package: KeychainAccess
      - package: WhisperKit

  ScraineeTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ScraineeTests
        excludes:
          - "Fixtures/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cpohl.scrainee.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Scrainee
      - package: GRDB
